[0m15:24:41.294997 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E77334FAD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E76DA30A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E773929850>]}


============================== 15:24:41.294997 | 928867db-3a52-4610-bf34-92e05c5b04fd ==============================
[0m15:24:41.294997 [info ] [MainThread]: Running with dbt=1.10.2
[0m15:24:41.301245 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\pgva005\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:24:41.305265 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\pgva005\Documents\EPRI_Prj\mssql_files\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:24:41.306287 [debug] [MainThread]: Command `dbt docs generate` failed at 15:24:41.306287 after 0.27 seconds
[0m15:24:41.307284 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E77379AFF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E773799040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E773FB9E50>]}
[0m15:24:41.308320 [debug] [MainThread]: Flushing usage events
[0m15:24:41.470321 [debug] [MainThread]: An error was encountered while trying to flush usage events
